apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: the-millennium-centre
  name: the-millennium-centre
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: the-millennium-centre
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: the-millennium-centre
    spec:
      containers:
      - image: docker.io/wolfjawan/the-millennium-centre:5e60f96
        imagePullPolicy: IfNotPresent
        name: the-millennium-centre
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
