---
version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/the-Millennium-Centre
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies for lint and test
          command: yarn
      - run:
          name: Set env variables
          command: 
            echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV  
      - run:
          name: build production
          command: yarn build   
      - run:
          name: Docker build the-millennium-centre
          command: |
            docker build -t wolfjawan/the-millennium-centre:$VERSION --build-arg version=$VERSION .
            docker tag wolfjawan/the-millennium-centre:$VERSION wolfjawan/the-millennium-centre:latest
      - run:
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Docker push the-millennium-centre
          command: docker push wolfjawan/the-millennium-centre
  # deploy_production:
  #   docker:
  #     - image: circleci/python:2.7-jessie
  #   working_directory: ~/repo
  #   steps:
  #     - setup_remote_docker
  #     - run:
  #         name: Set env variables
  #         command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
  #   kubectl set image deployment/the-millennium-centre the-millennium-centre=wolfjawan/the-millennium-centre:$VERSION
     
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test:
          filters:
            branches:
              only:    
                - master
      # - deploy_production:
      #     context: deployments
      #     requires:
      #       - build_test
      #     filters:
      #       branches:
      #         only:
      #           - master

