---
version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/the-Millennium-Centre
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "the-Millennium-Centre/yarn.lock" }}
      - setup_remote_docker
      - run:
          name: Install dependencies for lint and test
          command: yarn
      - run:
          name: Set env variables
          command: 
            echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV  
      - run:
          name: build production
          command: yarn build   
      - run:
          name: Docker build the-millennium-centre
          command: |
            docker build -t the-millennium-centre:$VERSION --build-arg version=$VERSION .
            docker tag the-millennium-centre:$VERSION the-millennium-centre:latest
      - run:
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Docker push the-millennium-centre
          command: docker push the-millennium-centre
  deploy_production:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - run:
          name: Set env variables
          command: echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
      - run:
          name: Install gnupg
          command: sudo apt -y install gnupg
      - run:
          name: Get kubeconfig
          command: aws s3 cp s3://$SECRETS_BUCKET/kubectl/config_cyfbot.gpg ./config.gpg
      - run:
          name: Decrypt kubeconfig and set KUBECONFIG
          command: gpg --yes --passphrase="$GPG_KEY" config.gpg
      - run:
          name: Update k8s deployments
          command: |
            KUBECONFIG=$(pwd)/config ./kubectl  set image deployment/themillenniumcentre-dep the-Millennium-Centre=the-Millennium-Centre:$VERSION
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test:
          filters:
            branches:
              only:    
                - master
      # - deploy_production:
      #     context: deployments
      #     requires:
      #       - build_test
      #     filters:
      #       branches:
      #         only:
      #           - master

