---
version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/the-Millennium-Centre
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: cd app && yarn
      - run:
          name: Set env variables
          command: 
            echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV  
      - run:
          name: build production
          command: cd app && yarn build   
      - run:
          name: Docker build the-millennium-centre
          command: |
            docker build -t wolfjawan/the-millennium-centre:$VERSION --build-arg version=$VERSION .
            docker tag wolfjawan/the-millennium-centre:$VERSION wolfjawan/the-millennium-centre:latest
      - run:
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Docker push the-millennium-centre
          command: docker push wolfjawan/the-millennium-centre
  deploy_production:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "dev-mohsen"
      - GOOGLE_PROJECT_ID: "dev-mohsen"
      - GOOGLE_COMPUTE_ZONE: "europe-west1-b"
      - GOOGLE_CLUSTER_NAME: "mohsen"     
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set env variables
          command: 
            echo 'export VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV      
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup_remote_docker
      - run: 
          name: Deploy to Kubernetes
          command:
            kubectl set image deployment/the-millennium-centre the-millennium-centre=docker.io/wolfjawan/the-millennium-centre:$VERSION
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test:
          filters:
            branches:
              only:    
                - master
      - deploy_production:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master

